'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LogoutButton } from "./components/LogoutButton";
import { ProfileImageLink } from "./components/ProfileImageLink";
import { useState, useEffect } from 'react';
import { AuthProvider, useAuth } from "./components/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const HeaderContent = () => {
  const {isLoggedIn} = useAuth()
  return (
    <nav className="justify-end flex gap-4">
      {isLoggedIn === true && <ProfileImageLink />}
      {isLoggedIn === true && <LogoutButton />}
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ログイン状態を保持するstate
  // 初期値をundefinedにして、判定完了後に表示を確定
  const [isLoggedIn, setIsLoggedIn] = useState<boolean | undefined>(undefined);;

  useEffect(() => {
    const token = localStorage.getItem('token');
    setIsLoggedIn(!!token); 
  }, []);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <AuthProvider>
          <header className="flex bg-cyan-400 justify-between align-middle min-w-max py-4 ">
            <a href='/events' className="text-2xl font-bold my-auto ml-16 text-white">Meetup_link</a>
            <HeaderContent />
          </header>
          <main className="w-10/12 max-w-screen-lg ml-16 mr-auto my-4">
            {children}
          </main>
          <footer>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
